import Footer from "../components/Footer";
import "@/css/Footer.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="content-contianer">
      <div className="childern">{children}</div>
      <Footer />
    </div>
  );
}
